#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www
if [ $# -eq 0 ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

domain=$1
subdomain=${2:-"www lb-01 web-01 web-02"}

function get_record_type() {
  local output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
  if echo "$output" | grep -q 'CNAME'; then
    echo "CNAME"
  else
    echo "A"
  fi
}

for s in $subdomain; do
  dest=$(dig +short $s.$domain | awk '{print $1}')
#   record=$(dig +short $s.$domain | awk '{print $4}')
  record=$(get_record_type $subdomain $domain)
  echo "The subdomain $s is a $record record and points to $dest"
done
